const data = {
  players:[
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16847-david-johnson-arizona-cardinals",
      name:"David Johnson",
      position: "RB",
      rank:1.2,
      team:"ARI",
      projected_points:283.1,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14967-leveon-bell-pittsburgh-steelers",
      name:"Le'Veon Bell",
      position: "RB",
      rank:2.3,
      team:"PIT",
      projected_points:265.50,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=17923-ezekiel-elliott-dallas-cowboys",
      name:"Ezekiel Elliott",
      position: "RB",
      rank:3.6,
      team:"DAL",
      projected_points:242.3,
      bye: 6,
    },
    {
      link:"https://www.fantasydata.com/nfl-stats/player-details.aspx?playerid=11056-antonio-brown-pittsburgh-steelers",
      name:"Antonio Brown",
      position:"WR",
      rank:3.8,
      team:"PIT",
      projected_points:209.90,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16389-odell-beckham-jr-new-york-giants",
      name:"Odell Beckham Jr.",
      position: "WR",
      rank:5.5,
      team:"NYG",
      projected_points:193.40,
      bye: 8,
    },
    {
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=13291-julio-jones-atlanta-falcons",
      name:"Julio Jones",
      position: "WR",
      rank:7.3,
      team:"ATL",
      projected_points:196,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16597-mike-evans-tampa-bay-buccaneers",
      name:"Mike Evans",
      position: "WR",
      rank:7.9,
      team:"TB",
      projected_points:188.80,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=11932-lesean-mccoy-buffalo-bills",
      name:"LeSean McCoy",
      position: "RB",
      rank:7.9,
      team:"BUF",
      projected_points:212,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16776-melvin-gordon-los-angeles-chargers",
      name:"Melvin Gordon",
      position: "RB",
      rank: 10.6,
      team:"LAC",
      projected_points:200.2,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=18067-jordan-howard-chicago-bears",
      name:"Jordan Howard",
      position: "RB",
      rank:10.9,
      team:"CHI",
      projected_points:201.3,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=12845-aj-green-cincinnati-bengals",
      name:"A.J. Green",
      position: "WR",
      rank:12.6,
      team:"CIN",
      projected_points:180.7,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16524-devonta-freeman-atlanta-falcons",
      name:"Devonta Freeman",
      position: "RB",
      rank:12.9,
      team:"ATL",
      projected_points:213.1,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16909-jay-ajayi-miami-dolphins",
      name:"Jay Ajayi",
      position: "RB",
      rank:13.1,
      team:"MIA",
      projected_points:193.70,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=4556-jordy-nelson-green-bay-packers",
      name:"Jordy Nelson",
      position: "WR",
      rank:14.6,
      team:"GB",
      projected_points:186.60,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=13124-demarco-murray-tennessee-titans",
      name:"DeMarco Murray",
      position: "RB",
      rank:16.6,
      team:"TEN",
      projected_points:196.30,
      bye: 8,
    },
    ,
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=17960-michael-thomas-new-orleans-saints",
      name:"Michael Thomas",
      position: "WR",
      rank:17.4,
      team:"NO",
      projected_points:169.90,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=11270-dez-bryant-dallas-cowboys",
      name:"Dez Bryant",
      position: "WR",
      rank:18.9,
      team:"DAL",
      projected_points:164.40,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14005-ty-hilton-indianapolis-colts",
      name:"T.Y. Hilton",
      position: "WR",
      rank:20.1,
      team:"IND",
      projected_points:163.80,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=2593-aaron-rodgers-green-bay-packers",
      name:"Aaron Rodgers",
      position: "QB",
      rank:20.9,
      team:"GB",
      projected_points:338.60,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=18803-leonard-fournette-jacksonville-jaguars",
      name:"Leonard Fournette",
      position: "RB",
      rank:21.9,
      team:"JAX",
      projected_points:172.20,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16771-todd-gurley-los-angeles-rams",
      name:"Todd Gurley",
      position: "RB",
      rank:23.2,
      team:"LAR",
      projected_points:191.10,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16765-amari-cooper-oakland-raiders",
      name:"Amari Cooper",
      position: "WR",
      rank:23.6,
      team:"OAK",
      projected_points:160.20,
      bye: 10,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=13460-doug-baldwin-seattle-seahawks",
      name:"Doug Baldwin",
      position: "WR",
      rank:23.9,
      team:"SEA",
      projected_points:146.40,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=13791-lamar-miller-houston-texans",
      name:"Lamar Miller",
      position: "RB",
      rank:24.1,
      team:"HOU",
      projected_points:176.90,
      bye: 7,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=4314-tom-brady-new-england-patriots",
      name:"Tom Brady",
      position: "QB",
      rank:25.4,
      team:"NE",
      projected_points:320.40,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=10974-rob-gronkowski-new-england-patriots",
      name:"Rob Gronkowski",
      position: "TE",
      rank:25.6,
      team:"NE",
      projected_points:156.50,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14986-deandre-hopkins-houston-texans",
      name:"DeAndre Hopkins",
      position: "WR",
      rank:28.0,
      team:"HOU",
      projected_points:148.50,
      bye: 7,
    },
    { 
      link:"",
      name:"Brandin Cooks",
      position: "WR",
      rank:28.1,
      team:"NE",
      projected_points:152.70,
      bye: 7,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=11197-demaryius-thomas-denver-broncos",
      name:"Demaryius Thomas",
      position: "WR",
      rank:32.5,
      team:"DEN",
      projected_points:152.60,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=18877-christian-mccaffrey-carolina-panthers",
      name:"Christian McCaffrey",
      position: "RB",
      rank:33.1,
      team:"CAR",
      projected_points:142.10,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16127-isaiah-crowell-cleveland-browns",
      name:"Isaiah Crowell",
      position: "RB",
      rank:34.7,
      team:"CLE",
      projected_points:170.20,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=7242-drew-brees-new-orleans-saints",
      name:"Drew Brees",
      position: "QB",
      rank:35.8,
      team:"NO",
      projected_points:309.78,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=12386-marshawn-lynch-oakland-raiders",
      name:"Marshawn Lynch",
      position: "RB",
      rank:36.6,
      team:"OAK",
      projected_points:154.60,
      bye: 10,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    ]
}
console.log(data)
for (i in data.player){
  console.log(i+':'+data.player[i])
var yo = $('<td>').append(i+':'+data.player[i])
$('body').append(yo)
}