const data = {
  players:[
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16847-david-johnson-arizona-cardinals",
      name:"David Johnson",
      position: "RB",
      rank:1.2,
      team:"ARI",
      projected_points:283.1,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14967-leveon-bell-pittsburgh-steelers",
      name:"Le'Veon Bell",
      position: "RB",
      rank:2.3,
      team:"PIT",
      projected_points:265.50,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=17923-ezekiel-elliott-dallas-cowboys",
      name:"Ezekiel Elliott",
      position: "RB",
      rank:3.6,
      team:"DAL",
      projected_points:242.3,
      bye: 6,
    },
    {
      link:"https://www.fantasydata.com/nfl-stats/player-details.aspx?playerid=11056-antonio-brown-pittsburgh-steelers",
      name:"Antonio Brown",
      position:"WR",
      rank:3.8,
      team:"PIT",
      projected_points:209.90,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16389-odell-beckham-jr-new-york-giants",
      name:"Odell Beckham Jr.",
      position: "WR",
      rank:5.5,
      team:"NYG",
      projected_points:193.40,
      bye: 8,
    },
    {
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=13291-julio-jones-atlanta-falcons",
      name:"Julio Jones",
      position: "WR",
      rank:7.3,
      team:"ATL",
      projected_points:196,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16597-mike-evans-tampa-bay-buccaneers",
      name:"Mike Evans",
      position: "WR",
      rank:7.9,
      team:"TB",
      projected_points:188.80,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=11932-lesean-mccoy-buffalo-bills",
      name:"LeSean McCoy",
      position: "RB",
      rank:7.9,
      team:"BUF",
      projected_points:212,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16776-melvin-gordon-los-angeles-chargers",
      name:"Melvin Gordon",
      position: "RB",
      rank: 10.6,
      team:"LAC",
      projected_points:200.2,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=18067-jordan-howard-chicago-bears",
      name:"Jordan Howard",
      position: "RB",
      rank:10.9,
      team:"CHI",
      projected_points:201.3,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=12845-aj-green-cincinnati-bengals",
      name:"A.J. Green",
      position: "WR",
      rank:12.6,
      team:"CIN",
      projected_points:180.7,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16524-devonta-freeman-atlanta-falcons",
      name:"Devonta Freeman",
      position: "RB",
      rank:12.9,
      team:"ATL",
      projected_points:213.1,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16909-jay-ajayi-miami-dolphins",
      name:"Jay Ajayi",
      position: "RB",
      rank:13.1,
      team:"MIA",
      projected_points:193.70,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=4556-jordy-nelson-green-bay-packers",
      name:"Jordy Nelson",
      position: "WR",
      rank:14.6,
      team:"GB",
      projected_points:186.60,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=13124-demarco-murray-tennessee-titans",
      name:"DeMarco Murray",
      position: "RB",
      rank:16.6,
      team:"TEN",
      projected_points:196.30,
      bye: 8,
    },
    ,
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=17960-michael-thomas-new-orleans-saints",
      name:"Michael Thomas",
      position: "WR",
      rank:17.4,
      team:"NO",
      projected_points:169.90,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=11270-dez-bryant-dallas-cowboys",
      name:"Dez Bryant",
      position: "WR",
      rank:18.9,
      team:"DAL",
      projected_points:164.40,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14005-ty-hilton-indianapolis-colts",
      name:"T.Y. Hilton",
      position: "WR",
      rank:20.1,
      team:"IND",
      projected_points:163.80,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=2593-aaron-rodgers-green-bay-packers",
      name:"Aaron Rodgers",
      position: "QB",
      rank:20.9,
      team:"GB",
      projected_points:338.60,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=18803-leonard-fournette-jacksonville-jaguars",
      name:"Leonard Fournette",
      position: "RB",
      rank:21.9,
      team:"JAX",
      projected_points:172.20,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16771-todd-gurley-los-angeles-rams",
      name:"Todd Gurley",
      position: "RB",
      rank:23.2,
      team:"LAR",
      projected_points:191.10,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16765-amari-cooper-oakland-raiders",
      name:"Amari Cooper",
      position: "WR",
      rank:23.6,
      team:"OAK",
      projected_points:160.20,
      bye: 10,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=13460-doug-baldwin-seattle-seahawks",
      name:"Doug Baldwin",
      position: "WR",
      rank:23.9,
      team:"SEA",
      projected_points:146.40,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=13791-lamar-miller-houston-texans",
      name:"Lamar Miller",
      position: "RB",
      rank:24.1,
      team:"HOU",
      projected_points:176.90,
      bye: 7,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=4314-tom-brady-new-england-patriots",
      name:"Tom Brady",
      position: "QB",
      rank:25.4,
      team:"NE",
      projected_points:320.40,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=10974-rob-gronkowski-new-england-patriots",
      name:"Rob Gronkowski",
      position: "TE",
      rank:25.6,
      team:"NE",
      projected_points:156.50,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14986-deandre-hopkins-houston-texans",
      name:"DeAndre Hopkins",
      position: "WR",
      rank:28.0,
      team:"HOU",
      projected_points:148.50,
      bye: 7,
    },
    { 
      link:"",
      name:"Brandin Cooks",
      position: "WR",
      rank:28.1,
      team:"NE",
      projected_points:152.70,
      bye: 7,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=11197-demaryius-thomas-denver-broncos",
      name:"Demaryius Thomas",
      position: "WR",
      rank:32.5,
      team:"DEN",
      projected_points:152.60,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=18877-christian-mccaffrey-carolina-panthers",
      name:"Christian McCaffrey",
      position: "RB",
      rank:33.1,
      team:"CAR",
      projected_points:142.10,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16127-isaiah-crowell-cleveland-browns",
      name:"Isaiah Crowell",
      position: "RB",
      rank:34.7,
      team:"CLE",
      projected_points:170.20,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=7242-drew-brees-new-orleans-saints",
      name:"Drew Brees",
      position: "QB",
      rank:35.8,
      team:"NO",
      projected_points:309.78,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=12386-marshawn-lynch-oakland-raiders",
      name:"Marshawn Lynch",
      position: "RB",
      rank:36.6,
      team:"OAK",
      projected_points:154.60,
      bye: 10,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=15048-travis-kelce-kansas-city-chiefs",
      name:"Travis Kelce",
      position: "TE",
      rank:37.1,
      team:"KC",
      projected_points:127.90,
      bye: 10,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14187-alshon-jeffery-philadelphia-eagles",
      name:"Alshon Jeffery",
      position: "WR",
      rank:37.4,
      team:"PHI",
      projected_points:131.60,
      bye: 10,
    },
    { 
      link:"",
      name:"Allen Robinson",
      position: "WR",
      rank:37.8,
      team:"JAX",
      projected_points:142.40,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16003-sammy-watkins-buffalo-bills",
      name:"Sammy Watkins",
      position: "WR",
      rank:38.8,
      team:"LAR",
      projected_points:145.50,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=18858-joe-mixon-cincinnati-bengals",
      name:"Joe Mixon",
      position: "RB",
      rank:39.5,
      team:"CIN",
      projected_points:152.60,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=13693-terrelle-pryor-washington-redskins",
      name:"Terrelle Pryor Sr.",
      position: "WR",
      rank:40.7,
      team:"WAS",
      projected_points:140.90,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16470-davante-adams-green-bay-packers",
      name:"Davante Adams",
      position: "WR",
      rank:43.0,
      team:"GB",
      projected_points:135.20,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=1658-greg-olsen-carolina-panthers",
      name:"Greg Olsen",
      position: "TE",
      rank:45.5,
      team:"CAR",
      projected_points:142.40,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14008-andrew-luck-indianapolis-colts",
      name:"Andrew Luck",
      position: "QB",
      rank:47.3,
      team:"IND",
      projected_points:290.34,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=9331-michael-crabtree-oakland-raiders",
      name:"Michael Crabtree",
      position: "WR",
      rank:47.6,
      team:"OAK",
      projected_points:144.80,
      bye: 10,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=15100-jordan-reed-washington-redskins",
      name:"Jordan Reed",
      position: "TE",
      rank:48.5,
      team:"WAS",
      projected_points:133,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=8355-julian-edelman-new-england-patriots",
      name:"Julian Edelman",
      position: "WR",
      rank:49.1,
      team:"NE",
      projected_points:123.10,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16668-carlos-hyde-san-francisco-49ers",
      name:"Carlos Hyde",
      position: "RB",
      rank:50.6,
      team:"SF",
      projected_points:146.10,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=18082-tyreek-hill-kansas-city-chiefs",
      name:"Tyreek Hill",
      position: "WR",
      rank:51.2,
      team:"KC",
      projected_points:131,
      bye: 10,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=732-matt-ryan-atlanta-falcons",
      name:"Matt Ryan",
      position: "QB",
      rank:51.6,
      team:"ATL",
      projected_points:288.90,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=15076-keenan-allen-los-angeles-chargers",
      name:"Keenan Allen",
      position: "WR",
      rank:52.6,
      team:"LAC",
      projected_points:130.10,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=11488-jimmy-graham-seattle-seahawks",
      name:"Jimmy Graham",
      position: "TE",
      rank:53.2,
      team:"SEA",
      projected_points:108.80,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14872-mike-gillislee-new-england-patriots",
      name:"Mike Gillislee",
      position: "RB",
      rank:54.5,
      team:"NE",
      projected_points:132.80,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=15261-spencer-ware-kansas-city-chiefs",
      name:"Spencer Ware",
      position: "RB",
      rank:55.8,
      team:"KC",
      projected_points:147.40,
      bye: 10,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=11063-emmanuel-sanders-denver-broncos",
      name:"Emmanuel Sanders",
      position: "WR",
      rank:55.9,
      team:"DEN",
      projected_points:134,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16020-jarvis-landry-miami-dolphins",
      name:"Jarvis Landry",
      position: "WR",
      rank:57.1,
      team:"MIA",
      projected_points:131.40,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16763-marcus-mariota-tennessee-titans",
      name:"Marcus Mariota",
      position: "QB",
      rank:57.5,
      team:"TEN",
      projected_points:283.72,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14536-russell-wilson-seattle-seahawks",
      name:"Russell Wilson",
      position: "QB",
      rank:57.9,
      team:"SEA",
      projected_points:305.38,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=7175-delanie-walker-tennessee-titans",
      name:"Delanie Walker",
      position: "TE",
      rank:62.6,
      team:"TEN",
      projected_points:100.40,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16146-martavis-bryant-pittsburgh-steelers",
      name:"Martavis Bryant",
      position: "WR",
      rank:62.7,
      team:"PIT",
      projected_points:130.70,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=15138-eddie-lacy-seattle-seahawks",
      name:"Eddie Lacy",
      position: "RB",
      rank:62.8,
      team:"SEA",
      projected_points:137.10,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16855-ty-montgomery-green-bay-packers",
      name:"Ty Montgomery",
      position: "RB",
      rank:63.0,
      team:"GB",
      projected_points:159.60,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14918-tyler-eifert-cincinnati-bengals",
      name:"Tyler Eifert",
      position: "TE",
      rank:65.2,
      team:"CIN",
      projected_points:91.90,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/team-depth-chart.aspx?team=DEN&name=Denver%20Broncos",
      name:"Denver",
      position: "DEF",
      rank:69.3,
      team:"DEN",
      projected_points:109,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=13337-mark-ingram-new-orleans-saints",
      name:"Mark Ingram",
      position: "RB",
      rank:69.4,
      team:"NO",
      projected_points:156,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=1181-martellus-bennett-green-bay-packers",
      name:"Martellus Bennett",
      position: "TE",
      rank:69.5,
      team:"GB",
      projected_points:91,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=13320-cam-newton-carolina-panthers",
      name:"Cam Newton",
      position: "QB",
      rank:70.6,
      team:"CAR",
      projected_points:288.14,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=5571-larry-fitzgerald-arizona-cardinals",
      name:"Larry Fitzgerald",
      position: "WR",
      rank:70.8,
      team:"ARI",
      projected_points:131.50,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/team-depth-chart.aspx?team=SEA&name=Seattle%20Seahawks",
      name:"Seattle",
      position: "DEF",
      rank:72.0,
      team:"SEA",
      projected_points:98,
      bye: 6,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16762-jameis-winston-tampa-bay-buccaneers",
      name:"Jameis Winston",
      position: "QB",
      rank:73.1,
      team:"TB",
      projected_points:289.54,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=15020-cj-anderson-denver-broncos",
      name:"C.J. Anderson",
      position: "RB",
      rank:73.2,
      team:"DEN",
      projected_points:133.40,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=18872-dalvin-cook-minnesota-vikings",
      name:"Dalvin Cook",
      position: "RB",
      rank:74.4,
      team:"MIN",
      projected_points:143.50,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/team-depth-chart.aspx?team=HOU&name=Houston%20Texans",
      name:"Houston",
      position: "DEF",
      rank:75.6,
      team:"HOU",
      projected_points:109,
      bye: 7,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=3807-ben-roethlisberger-pittsburgh-steelers",
      name:"Ben Roethlisberger",
      position: "QB",
      rank:76.3,
      team:"PIT",
      projected_points:264.54,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=11611-golden-tate-detroit-lions",
      name:"Golden Tate",
      position: "WR",
      rank:77.6,
      team:"DET",
      projected_points:141.60,
      bye: 7  ,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=4807-adrian-peterson-new-orleans-saints",
      name:"Adrian Peterson",
      position: "RB",
      rank:77.9,
      team:"NO",
      projected_points:115.10,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=2982-stephen-gostkowski-new-england-patriots",
      name:"Stephen Gostkowski",
      position: "K",
      rank:77.9,
      team:"NE",
      projected_points:138,
      bye: 9,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=14688-justin-tucker-baltimore-ravens",
      name:"Justin Tucker",
      position: "K",
      rank:78.3,
      team:"BAL",
      projected_points:128,
      bye: 10,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/team-depth-chart.aspx?team=KC&name=Kansas%20City%20Chiefs",
      name:"Kansas City",
      position: "DEF",
      rank:78.8,
      team:"KC",
      projected_points:118,
      bye: 10,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=3943-desean-jackson-tampa-bay-buccaneers",
      name:"DeSean Jackson",
      position: "WR",
      rank:79.5,
      team:"TB",
      projected_points:121,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=12296-legarrette-blount-philadelphia-eagles",
      name:"LeGarrette Blount",
      position: "RB",
      rank:79.8,
      team:"PHI",
      projected_points:111.10,
      bye: 10,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=11667-brandon-marshall-new-york-giants",
      name:"Brandon Marshall",
      position: "WR",
      rank:80.2,
      team:"NYG",
      projected_points:117.70,
      bye: 8,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16866-jamison-crowder-washington-redskins",
      name:"Jamison Crowder",
      position: "WR",
      rank:82.1,
      team:"WAS",
      projected_points:121.20,
      bye: 5,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16550-kelvin-benjamin-carolina-panthers",
      name:"Kelvin Benjamin",
      position: "WR",
      rank:83,
      team:"CAR",
      projected_points:136.40,
      bye: 11,
    },
    { 
      link:"https://fantasydata.com/nfl-stats/player-details.aspx?playerid=16232-donte-moncrief-indianapolis-colts",
      name:"Donte Moncrief",
      position: "WR",
      rank:83.2,
      team:"IND",
      projected_points:117.90,
      bye: 11,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    { 
      link:"",
      name:"",
      position: "",
      rank:,
      team:"",
      projected_points:,
      bye: ,
    },
    ]
}
console.log(data)
for (i in data.player){
  console.log(i+':'+data.player[i])
var yo = $('<td>').append(i+':'+data.player[i])
$('body').append(yo)
}